### ISSUE TITLE
How can I enable MMBarricade for `AFHTTPSessionManager` in AFNetworking ?

### ISSUE THREAD

**Issue by zhugexiaobo** [mutualmobile/MMBarricade#3]
> `AFHTTPSessionManager` is a subclass of `AFURLSessionManager` with convenience methods for making HTTP requests.

It seems we can't get `NSURLSessionConfiguration` before creating the session.

**Comment by jcgsxr** [comment]
Try creating the session and pass it into the initializer for `AFHTTPSessionManager`. So something like:

```
NSURLSessionConfiguration *config = [NSURLSessionConfiguration defaultSessionConfiguration];
[MMBarricade enableForSessionConfiguration:config];
AFHTTPSessionManager *manager = [[AFHTTPSessionManager alloc] initWithBaseURL:[NSURL URLWithString:@"http://www.baseurl.com"] sessionConfiguration:config];
```

**Comment by johntmcintosh** [comment]
What @jcgsxr describes should be right on. @zhugexiaobo feel free to let me know if you're still having trouble, but I think that should get you in the right direction.

**Comment by zhugexiaobo** [comment]
Yes, it works. Thanks for both of you. I forgot to close this issue.
