### ISSUE TITLE
Barricade not working in iOS 9

### ISSUE THREAD

**Issue by piercifani** [mutualmobile/MMBarricade#4]
Enabling the barricade using the `enableForSessionConfiguration:` API is not working in iOS 9. The `NSURLProtocol` methods (`canInitWithRequest`, `startLoading`, etc) are not called by the operating system.

I don't know if this is an iOS9 bug, but it's something worth to look at

**Comment by piercifani** [comment]
I think I've found the core issue: `NSURLSession`'s initializer is ignoring the `configuration` parameter. You can see this issue with this snippet of code:

```
let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
print(configuration)
let session = NSURLSession(configuration: configuration, delegate: nil, delegateQueue: nil)
print(session.configuration)
```

This will print out the following on iOS 8

```
<NSURLSessionConfiguration: 0x7fd82a4466b0>
<NSURLSessionConfiguration: 0x7fd82a4466b0>
```

But on iOS 9: 

```
<__NSCFURLSessionConfiguration: 0x7fe17863e880>
<__NSCFURLSessionConfiguration: 0x7fe178650470>
```

I'll be reporting this to Apple with a Radar.

**Comment by piercifani** [comment]
Radar opened: rdar://22305621

**Comment by johntmcintosh** [comment]
Thanks for the report and radar, @piercifani! I'll take a look as well and see if there's anything additional I can find.

**Comment by piercifani** [comment]
Apple got back to me. This is their response:

```
Hi Pierluigi,

This is a follow-up regarding Bug ID# 22305621.   

Please update your report directly at http://bugreport.apple.com for the fastest response.  Please do not email your updates.

Engineering has determined that this issue behaves as intended based on the following information:

The configuration is not ignored. You’re just getting a different copy back whenever you call session.configuration. The reason for this is so that the configuration can’t be modified after the session is created.


Developer Bug Reporting Team 
Apple Worldwide Developer Relations
https://developer.apple.com
```

So... How can we work around this?

**Comment by johntmcintosh** [comment]
@piercifani thanks for the update. Could you post a snippet of the setup code that you're using?

**Comment by piercifani** [comment]
Sure! 

On the `setUp` of the unit tests:

```
- (void)setUp
{
    [super setUp];

    self.client = [APIClient clientWithProtocol:@"http" baseURL:@"pre.wallapop.com" port:80];

    [MMBarricade setupWithInMemoryResponseStore];
    [MMBarricade enableForSessionConfiguration:self.client.sessionConfiguration];
}
```

And for the `APIClient` class, I create the `NSURLSessionConfiguration` on init:

```
    public init () {
        self.networkManager = Alamofire.Manager(configuration:NSURLSessionConfiguration.defaultSessionConfiguration())
    }
```

And the getter you see on the unit tests is here:

```
    public var sessionConfiguration : NSURLSessionConfiguration {
        return networkManager.session.configuration
    }
```

This works as expected on iOS7-8, but since Apple changed the behavior of the `NSURLSession`'s configuration getter, I don't know how to work around this on my side.

**Comment by johntmcintosh** [comment]
Ahh - yep, I remember seeing something about that. They did move to an approach where you cannot modify a session configuration once's it's given to a session. The way I've worked around this before is to setup my networking code so that I'm enabling barricade on a session, then passing in then session configuration rather than creating one internally. Then I'd have something like this:

```
- (void)setUp
{
    [super setUp];

    NSURLSessionConfiguration *sessionConfiguration = [NSURLSessionConfiguration defaultSessionConfiguration];
    [MMBarricade setupWithInMemoryResponseStore];
    [MMBarricade enableForSessionConfiguration:sessionConfiguration];
    self.client = [APIClient clientWithSessionConfiguration:sessionConfiguration protocol:@"http" baseURL:@"pre.wallapop.com" port:80];
}
```

and your `init` could become something like:

```
public init (sessionConfiguration: NSURLSessionConfiguration) {
    self.networkManager = Alamofire.Manager(configuration:sessionConfiguration)
}
```

I wish there was a more straightforward way to make this easier from the the implementor's perspective, but I haven't come up with anything other than swizzling `defaultSessionConfiguration`, which I have been hesitant to do.

**Comment by piercifani** [comment]
Interesting approach, I didn't thought of swizzling... 

That definitely works, maybe it's not the best way of doing it, but it can get us out of this hassle!
